[ros2] Enable Save
ros-visualization/rqt_bag pull request #142
Opened 2023-05-19 10:51 UTC by Yadunund

Merge #127 first

This PR
* Enables the save button for users to click once they begin recording
* Updates the save button's callback to stop the recording which will save the bag file and metadata.yaml

Tested as seen in the video below.

https://github.com/ros-visualization/rqt_bag/assets/13482049/36f9bb7c-6ed2-473c-ac4b-0e0c2652bc86

2023-05-19 12:17 UTC, clalancette commented
> Merge #127 first

Presumably you mean "merge #141 first", correct?

2023-05-19 15:36 UTC, Yadunund commented
> > Merge #127 first
> 
> Presumably you mean "merge #141 first", correct?

Ah yes 😅

2023-05-19 19:12 UTC, clalancette reviewed
I mostly have a question about what it means to "save" in `rqt_bag`.  There are at least two interpretations that I can come up with:

1. Save whatever is currently in memory to a bag file, and stop the recording (that seems to be what this PR implements).
2. Save whatever is currently in memory to a bag file, and continue to record.

It's also possible that I'm misunderstanding all of this completely.  Regardless, which semantic are we going for here?

2023-05-22 09:49 UTC, Yadunund commented
Whoops sorry for not explaining the approach in the PR description.

You're right, this PR implements 1). 
Looking at the code, the existing implementation is only expecting to save a specific region of a recorded bag that been loaded into the timeline. There are some internal APIs to extract this region but the frontend UI does not provide any means to select a region.  So in this PR I updated the implementation to stop the recording (which saves the bag) when save is clicked.

I think 2) would not be possible without some refactoring. Currently we can toggle the record button but what that does is pause/unpausing the writing to the same bag. But during this toggle, the plugin is still in a "recording" state; but just that it doesn't write any data to the bag. So you can record for a bit, pause, resume recording, save bag. Presently the creation of bag requires the plugin to not be in "recording" state so some effort is needed to implement this.

Happy to modify this PR as per any recommendations.

2023-05-22 20:41 UTC, clalancette commented
All right, thanks for the explanation.  Even though I find that a somewhat confusing semantic, it is an improvement over "doesn't work at all" :).  I'll leave one other minor request inline, then we can run CI on it.

2023-05-22 20:42 UTC, clalancette requested changes

2023-05-22 20:42 UTC, clalancette commented on rqt_bag/src/rqt_bag/bag_widget.py
> +        # todo: Enable this code pathway when support for extracting regions
Our typical style here is `TODO(username)` following the Google guidelines:

```suggestion
        # TODO(Yadunund): Enable this code pathway when support for extracting regions
```

2023-05-23 13:14 UTC, clalancette approved these changes

2023-05-23 13:15 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18780)](http://ci.ros2.org/job/ci_linux/18780/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13305)](http://ci.ros2.org/job/ci_linux-aarch64/13305/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19522)](http://ci.ros2.org/job/ci_windows/19522/)

2023-05-23 16:12 UTC, merged

2023-05-24 02:13 UTC, Yadunund commented
@mergifyio backport iron